language: python

services:
  - docker

before_install:
  - docker --version
  - docker-compose build web 
  - docker-compose up -d
  - docker ps -a

script:
  - docker-compose run --name test web python manage.py db upgrade
  - docker-compose exec test pytest