language: python

services:
  - docker

before_install:
  - docker --version
  - docker-compose build web 
  - lsof -i :5432
  - docker-compose up -d
  - docker ps -a
  - docker-compose run --rm web sh

script:
  - pytest