language: python

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose build web 
  - docker-compose up -d
  - docker ps -a

script:
  - docker-compose run web python manage.py db upgrade
  - docker-compose exec web pytest