version: '3'
services:
  web:
    build: .
    image: web
    command: "gunicorn -c gunicorn.conf.py client.wsgi:app --reload"
    ports:
      - 8000:8000
    volumes:
      - .:/stellar-SMS
  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar
    volumes:
      - db_volume:/var/lib/postgresql

  federation:
    image: web
    command: "./federation_"
    ports: 
      - 8002:8002
    depends_on: 
      - postgres
volumes:
  db_volume: