version: '3'
services:
  web:
    image: stellar-sms:1.0.0
    build: .
    command: "gunicorn -c gunicorn.conf.py client.wsgi:app"
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar
    ports:
        - 5432:5432