version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
  redis:
    image: redis:latest
  web:
    build: .
    image: web
    command: "gunicorn -c gunicorn.conf.py client.wsgi:app"
    ports:
      - 8000:8000
    env_file:
      - env
    volumes:
      - .:/stellar-SMS
  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar
    volumes:
      - db_volume:/var/lib/postgresql
  celery:
    image: web
    command: celery worker -A client.factory:celery -l info
    env_file:
      - env
    depends_on: 
      - redis
      - rabbitmq
      - postgres

volumes:
  db_volume: