version: '3'
services:
  web:
    build: .
    image: web
    command: "gunicorn -c gunicorn.conf.py client.wsgi:app"
    ports:
      - 8000:8000
    volumes:
      - .:/stellar-SMS
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_DB=stellar
    ports:
        - 5432:5432
  federation:
    image: web
    command: "./federation/federation"