"""empty message

Revision ID: 70e1cf8d7a57
Revises: 45935e1ad102
Create Date: 2019-06-05 09:37:53.130441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e1cf8d7a57'
down_revision = '45935e1ad102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('time_created', sa.Date(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.String(length=16), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=True),
    sa.Column('fee', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_asset'), 'payments', ['asset'], unique=False)
    op.create_index(op.f('ix_payments_destination'), 'payments', ['destination'], unique=False)
    op.create_index(op.f('ix_payments_time_created'), 'payments', ['time_created'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_time_created'), table_name='payments')
    op.drop_index(op.f('ix_payments_destination'), table_name='payments')
    op.drop_index(op.f('ix_payments_asset'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
