"""empty message

Revision ID: cfc92023cbaf
Revises: a536774e0b2b
Create Date: 2019-06-06 11:18:11.691138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfc92023cbaf'
down_revision = 'a536774e0b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address'), 'addresses', ['address'], unique=True)
    op.create_index(op.f('ix_addresses_username'), 'addresses', ['username'], unique=False)
    op.drop_index('ix_alias_address', table_name='alias')
    op.drop_index('ix_alias_username', table_name='alias')
    op.drop_table('alias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='alias_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alias_pkey')
    )
    op.create_index('ix_alias_username', 'alias', ['username'], unique=True)
    op.create_index('ix_alias_address', 'alias', ['address'], unique=True)
    op.drop_index(op.f('ix_addresses_username'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
